# Statistical Inference - Quiz 3 - Intervals, Testing, & Pvalues
#### Course available at [Coursera](https://www.coursera.org/learn/statistical-inference/)
***
**1 -** In a population of interest, a sample of 9 men yielded a sample average brain volume of 1,100cc and a standard deviation of 30cc. What is a 95% Student's T confidence interval for the mean brain volume in this new population?

```{R echo = TRUE}
# Rule: mean + c(-1, 1) * qt(p, n-1) * standard error
# Standard error = s/sqrt(n)
mu <- 1100
s <- 30
n <- 9
se <- s/sqrt(n)

round(mu + c(-1, 1) * qt(.975, n-1) * se)
```

**2 -** A diet pill is given to 9 subjects over six weeks. The average difference in weight (follow up - baseline) is -2 pounds. What would the standard deviation of the difference in weight have to be for the upper endpoint of the 95% T confidence interval to touch 0?

```{R echo = TRUE}
# Rule: upperEP = mu + qt(p, df) * sd / sqrt(n)
# sd = ?
# upperEP = mu * sqrt(n) + qt(p, n-1) * sd
# upperEP - mu * sqrt(n) = qt(p, n-1) * sd
# sd = upperEP - mu * sqrt(n) / qt(p, n-1)

upperEP = 0
mu = -2
n = 9
p = .975

round(upperEP - mu * sqrt(n) / qt(p, n-1), 2)
```
**3 -** In an effort to improve running performance, 5 runners were either given a protein supplement or placebo. Then, after a suitable washout period, they were given the opposite treatment. Their mile times were recorded under both the treatment and placebo, yielding 10 measurements with 2 per subject. The researchers intend to use a T test and interval to investigate the treatment. Should they use a paired or independent group T test and interval?   

A paired interval.

**4 -** In a study of emergency room waiting times, investigators consider a new and the standard triage systems. To test the systems, administrators selected 20 nights and randomly assigned the new triage system to be used on 10 nights and the standard system on the remaining 10 nights. They calculated the nightly median waiting time (MWT) to see a physician. The average MWT for the new system was 3 hours with a variance of 0.60 while the average MWT for the old system was 5 hours with a variance of 0.68. Consider the 95% confidence interval estimate for the differences of the mean MWT associated with the new system. Assume a constant variance. What is the interval? Subtract in this order (New System - Old System).

```{R echo = TRUE}
# Rule (pve): ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2)
# Rule 2 (interval): (m1 - m2) + c(-1, 1) * qt(p + (1 - p)/2, (n1 + n2 - 2)) * sqrt(pve) * sqrt(1/n1 + 1/n2)
# pooled variance estimate (pve) = ?
# interval = ?

n_new <- n_old <- 10
mu_new <- 3
var_new <- .60
mu_old <- 5
var_old <- .68
p <- .95

pve <- ((n_new - 1) * var_new + (n_old - 1) * var_old) / (n_new + n_old - 2)

round((mu_new - mu_old) + c(-1, 1) * qt(p + (1 - p)/2, (n_new + n_old - 2)) * sqrt(pve) *
  sqrt((1 / n_new) + (1 / n_old)), 2)
```

**5 -** Suppose that you create a 95% T confidence interval. You then create a 90% interval using the same data. What can be said about the 90% interval with respect to the 95% interval?

The interval will be narrower.

**6 -** To further test the hospital triage system, administrators selected 200 nights and randomly assigned a new triage system to be used on 100 nights and a standard system on the remaining 100 nights. They calculated the nightly median waiting time (MWT) to see a physician. The average MWT for the new system was 4 hours with a standard deviation of 0.5 hours while the average MWT for the old system was 6 hours with a standard deviation of 2 hours. Consider the hypothesis of a decrease in the mean MWT associated with the new treatment.
What does the 95% independent group confidence interval with unequal variances suggest vis a vis this hypothesis? (Because there's so many observations per group, just use the Z quantile instead of the T.)

```{R echo = TRUE}
# Rule (standard error): sqrt(s1^2 / n1 + s2^2 / n2)
# Rule 2 (interval): (m2 - m1) + c(-1, 1) * qnorm(p) * standard error

n_new <- n_old <- 100
mu_new <- 4
sd_new <- .5
mu_old <- 6
sd_old <- 2
p <- .975

se <- sqrt(((sd_new ^ 2) / n_new) + ((sd_old ^ 2) / n_old))
round(((mu_old - mu_new) + c(-1, 1) * qnorm(p) * se) , 2)
```

**7 -** Suppose that 18 obese subjects were randomized, 9 each, to a new diet pill and a placebo. Subjects’ body mass indices (BMIs) were measured at a baseline and again after having received the treatment or placebo for four weeks. The average difference from follow-up to the baseline (followup - baseline) was −3 kg/m2 for the treated group and 1 kg/m2 for the placebo group. The corresponding standard deviations of the differences was 1.5 kg/m2 for the treatment group and 1.8 kg/m2 for the placebo group.
Does the change in BMI over the four week period appear to differ between the treated and placebo groups? Assuming normality of the underlying data and a common population variance, calculate the relevant *90%* t confidence interval. Subtract in the order of (Treated - Placebo) with the smaller (more negative) number first.

```{R echo = TRUE}
# Rule (pve): ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2)
# Rule 2 (interval): (m1 - m2) + c(-1, 1) * qt(p + (1 - p)/2, (n1 + n2 - 2)) * sqrt(pve) * sqrt(1/n1 + 1/n2)

n_pill <- n_placebo <- 9
mu_pill <- -3
sd_pill <- 1.5
mu_placebo <- 1
sd_placebo <- 1.8
p <- .90

pve <- (((n_pill - 1) * (sd_pill ^ 2)) + ((n_placebo - 1) * (sd_placebo ^ 2))) / 
  (n_pill + n_placebo - 2)

round((mu_pill - mu_placebo) + c(-1, 1) * qt(p + (1 - p)/2, (n_pill + n_placebo - 2)) * 
        sqrt(pve) * sqrt((1 / n_pill) + (1 / n_placebo)), 3)
```

***