# Statistical Inference - Quiz 1 - Probability & Expected Values
#### Course available at [Coursera](https://www.coursera.org/learn/statistical-inference/)
***
**1 -** Consider influenza epidemics for two parent heterosexual families. Suppose that the probability is 17% that at least one of the parents has contracted the disease. The probability that the father has contracted influenza is 12% while the probability that both the mother and father have contracted the disease is 6%. What is the probability that the mother has contracted influenza?   

```{R echo = TRUE}
# Rule: P(A ∪ B) = P(A) + P(B) - P(A ∩ B)
# P(A) = mother has contracted influenza = ?%
# P(B) = father has contracted influenza = 12%
# P(A ∪ B) = at least one of the parents has contracted influenza = 17%
# P(A ∩ B) = both of the parents has contracted influenza = 6%
# 17 = P(A) + 12 - 6
# P(A) = 12 - 6 - 17
(12 - 6 - 17) * (-1)
```

**2 -** A random variable, *X* is uniform, a box from 0 to 1 of height 1. (So that its density is *f(x)=1* for *0≤x≤1*.) What is its 75th percentile?

```{R echo = TRUE}
# Must use qunif() because the variable X is uniform.
qunif(.75, 0 , 1)
```

**3 -** You are playing a game with a friend where you flip a coin and if it comes up heads you give her *X* dollars and if it comes up tails she gives you *Y* dollars. The probability that the coin is heads is *p* (some number between 0 and 1.) What has to be true about *X* and *Y* to make so that both of your expected total earnings is 0. The game would then be called “fair”.  

*p/(1-p) = Y/X*

**4 -** A density that looks like a normal density (but may or may not be exactly normal) is exactly symmetric about zero. (Symmetric means if you flip it around zero it looks the same.) What is its median?   

The median is 0. Because 50% of the values are below 0 and 50% are above it.

**5 -** Consider the following PMF shown below in R

```{R echo = TRUE}
x <- 1:4
p <- x/sum(x)
temp <- rbind(x, p)
rownames(temp) <- c("X", "Prob")
temp
```
What is the mean?

```{R echo = TRUE}
mean(sum(temp["X", ] * temp["Prob", ]))
```

**6 -** A [web site](www.medicine.ox.ac.uk/bandolier/band64/b64-7.html) for home pregnancy tests cites the following: “When the subjects using the test were women who collected and tested their own samples, the overall sensitivity was 75%. Specificity was also low, in the range 52% to 75%.” Assume the lower value for the specificity. Suppose a subject has a positive test and that 30% of women taking pregnancy tests are actually pregnant. What number is closest to the probability of pregnancy given the positive test?

```{R echo = TRUE}
# Rule: P(D | +) = (P(+ | D) * P(D)) / (P(+ | D) * P(D) + P(+ | ~D) * P(~D))
#       P(D | +) = (P(+ | D) * P(D)) / (P(+ | D) * P(D) + (1 - P(+ | ~D)) * (1 - P(D)))
# P(+ | D) = Sensitivity = .75
# P(+ | ~D) = Specificity = .52
# D = are pregnant = .30
round((.75 * .30)/((.75 * .30) + ((1 - .52) * (1 - .30))), 2) * 100
```
***